### ISSUE TITLE
Handle `mmr_meta` if it's not single

### ISSUE THREAD

**Issue by rkdud007** [HerodotusDev/hdp#61]
### Context
current `input.json` cairo format is assuming to have only 1 mmr is containing all the batched tasks. 

However, the goal of this batch task is to have multiple independent tasks to be proven in one process and unlike mainnet testnet have chunked numbers of MMR exist so the assume that all batched tasks will contain in one mmr might incorrect case. 

### Suggestion
`mmr_meta` should be array of multiple mmrs 
and each header object have one field which identifies mmr id and size.

**Comment by rkdud007** [comment]
I think this is pretty high priority as we can now introduce multi-tasks in one batch -- because we cannot handle mutliple MMR, there is limitation around specifying block number range --
wdyt of suggestion that i listed above? @petscheit

**Comment by petscheit** [comment]
Can you explain what you mean with chunked number of MMRs? The way I understand it, every MMR root should contain every header, that is known until that point. I understand that we would need this in a multi-chain situation, but for a single chain execution I don't follow fully

**Comment by rkdud007** [comment]
even regarding the single chain execution, we not storing all block headers in one single MMR currently. ( to be more accurate, for not Ethereum mainnet case we use multi MMRs ) 

ex. smth like this.
mmr id 1 : [ 0~100]
mmr id 2 : [100 ~200] 

So if we just pass 1 MMR per batch, the range of available blocks are limited due to the specific id of MMR

**Comment by rkdud007** [comment]
endedup we can assume always the single MMR in one chain, lmk once Sepolia also get whole blocks in single MMR @marcellobardus
